### ISSUE TITLE
Useless issue

### ISSUE THREAD

**Issue by folkvir** [orichalque/uselesscompression#1]
This is a useless issue about a useless compression scheme.

Can you replace this useless image of toad with this one?

![green_toad_for_sttsg](https://user-images.githubusercontent.com/7128943/48265950-3eeabd80-e42e-11e8-9290-d1136700fb2b.png)

**Comment by tbezierslafosse** [comment]
I understand your concern. A fix will be published soon

**Comment by tbezierslafosse** [comment]
fixed #c52381c
![fixed](https://raw.githubusercontent.com/orichalque/uselesscompression/master/src/test/resources/output.png)

**Comment by folkvir** [comment]
Ahah this has a better quality now. 
Please reopen this issue, because its purpose is to be a USELESS OPENED ISSUE!

**Comment by tbezierslafosse** [comment]
you should open an issue for that
